project_id = "vanhfllipocroenismcf"

[functions.admin-actions]
verify_jwt = false

[functions.get-signed-urls]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
