// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// These are public/safe values — the anon key is protected by Row Level Security,
// not by secrecy. Hardcoded so the app works in all build environments
// (including Lovable's CI pipeline which does not inject .env variables).
const SUPABASE_URL = "https://vanhfllipocroenismcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhbmhmbGxpcG9jcm9lbmlzbWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3Nzc4NDQsImV4cCI6MjA4NjM1Mzg0NH0.7kgXj-MzYvFEnG-5_WklQKObws4FeDPToikzPnwqFrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});